name = "seithi-web"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2024-02-22"

[[d1_databases]]
binding = "DB"
database_name = "seithi-db"
database_id = "5053c95a-48a9-47b4-bafd-12a985b57743"
